### Products index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/2.json

### Products create

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "image_url": "test url",
  "price": "1"
}

### Products update
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
  "name": "Changed name",
  "image_url": "Changed URL"
}

### Products delete

DELETE http://localhost:3000/products/10.json