@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ4MDcwMjN9.7OcHlZMWVYh-AK_7qEDhzbYid8KdK8RVGSPJhzEyALY

######################################################

### Products index
GET http://localhost:3000/products.json


### Products show
GET http://localhost:3000/products/1.json

### Products create

POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "test name",
  "description": "test description",
  "price": "1",
  "supplier_id": "1"
}

### Products update
PATCH http://localhost:3000/products/12.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Changed name",
  "image_url": "Changed URL",
  "price": -1
}

### Products delete

DELETE http://localhost:3000/products/12.json
Authorization: Bearer {{jwt}}

######################################################

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Fourth User",
  "email": "test4@test.com",
  "password": "password",
  "password_confirmation": "password"
}

######################################################

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

######################################################

### Orders index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Orders show
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

### Orders create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

######################################################

### Carted_Products index

GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}

### Carted_Products create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 2,
  "quantity": 1
}

### Carted_Products destroy
DELETE http://localhost:3000/carted_products/1.json
Authorization: Bearer {{jwt}}