### Products index
GET http://localhost:3000/products

### Products show
GET http://localhost:3000/products/2

### Products create

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "image_url": "test url",
  "price": "1"
}

### Products update
PATCH http://localhost:3000/products/5
Content-Type: application/json

{
  "name": "Updated name",
  "description": "Updated description",
  "image_url": "Updated URL",
  "price": "2"
}